version: '3.5'

services:
  app:
    build: .
    restart: "no"
    ports:
      - 8080:8080

  db:
    image: postgres
    environment:
      POSTGRES_USER: avtara
      POSTGRES_PASSWORD: avtara112
      POSTGRES_DB: travairdb
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmqq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

volumes:
  postgres: