// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	users "github.com/avtara/travair-api/businesses/users"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Activation provides a mock function with given fields: ctx, userID
func (_m *Service) Activation(ctx context.Context, userID string) (*users.Domain, error) {
	ret := _m.Called(ctx, userID)

	var r0 *users.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) *users.Domain); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetID provides a mock function with given fields: ctx, userID
func (_m *Service) GetID(ctx context.Context, userID uuid.UUID) (uint, error) {
	ret := _m.Called(ctx, userID)

	var r0 uint
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) uint); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(uint)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *Service) Login(ctx context.Context, email string, password string) (*users.Domain, error) {
	ret := _m.Called(ctx, email, password)

	var r0 *users.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *users.Domain); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Registration provides a mock function with given fields: ctx, data
func (_m *Service) Registration(ctx context.Context, data *users.Domain) (*users.Domain, error) {
	ret := _m.Called(ctx, data)

	var r0 *users.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *users.Domain) *users.Domain); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *users.Domain) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
