// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// UploadLocal provides a mock function with given fields: file, nameFolder
func (_m *Repository) UploadLocal(file *multipart.FileHeader, nameFolder string) (string, error) {
	ret := _m.Called(file, nameFolder)

	var r0 string
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader, string) string); ok {
		r0 = rf(file, nameFolder)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*multipart.FileHeader, string) error); ok {
		r1 = rf(file, nameFolder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
