// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	reservations "github.com/avtara/travair-api/businesses/reservations"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetByDate provides a mock function with given fields: ctx, domain
func (_m *Repository) GetByDate(ctx context.Context, domain *reservations.Domain) error {
	ret := _m.Called(ctx, domain)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *reservations.Domain) error); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store provides a mock function with given fields: ctx, domain
func (_m *Repository) Store(ctx context.Context, domain *reservations.Domain) (*reservations.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 *reservations.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *reservations.Domain) *reservations.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reservations.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *reservations.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
