// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	reservations "github.com/avtara/travair-api/businesses/reservations"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Reservation provides a mock function with given fields: ctx, data
func (_m *Service) Reservation(ctx context.Context, data *reservations.Domain) (*reservations.Domain, error) {
	ret := _m.Called(ctx, data)

	var r0 *reservations.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *reservations.Domain) *reservations.Domain); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reservations.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *reservations.Domain) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
